export default {
  Search: () => import('./Search'),
  Dashboard: () => import('./Dashboard'),
  UserProfile: () => import('./UserProfile'),
  UserForm: () => import('./UserForm'),
  UserList: () => import('./UserList'),
  RoleForm: () => import('./RoleForm'),
  RoleList: () => import('./RoleList'),
  VesselForm: () => import('./VesselForm'),
  VesselList: () => import('./VesselList'),
  VesselIMOReport: () => import('./VesselIMOReport'),
  PortForm: () => import('./PortForm'),
  PortList: () => import('./PortList'),
  SeafarerForm: () => import('./SeafarerForm'),
  SeafarerList: () => import('./SeafarerList'),
  SeafarerContractForm: () => import('./SeafarerContractForm'),
  SeafarerContractList: () => import('./SeafarerContractList'),
  CrewRequestForm: () => import('./CrewRequestForm'),
  CrewRequestList: () => import('./CrewRequestList'),
  TaskList: () => import('./TaskList'),
  DepartmentForm: () => import('./DepartmentForm'),
  DepartmentList: () => import('./DepartmentList'),
  ActivityList: () => import('./ActivityList'),
  CashRequisitionForm: () => import('./CashRequisitionForm'),
  CashRequisitionList: () => import('./CashRequisitionList'),
  AuditList: () => import('./AuditList'),
  PaymentRequisitionForm: () => import('./PaymentRequisitionForm'),
  PaymentRequisitionList: () => import('./PaymentRequisitionList'),
  // QuotationForm: () => import('./QuotationForm'),
  // QuotationList: () => import('./QuotationList'),
  FlightReservationForm: () => import('./FlightReservationForm'),
  FlightReservationList: () => import('./FlightReservationList'),
  FlightReservationQuotationForm: () =>
    import('./FlightReservationQuotationForm'),
  FlightReservationQuotationList: () =>
    import('./FlightReservationQuotationList'),
  HolidayForm: () => import('./HolidayForm'),
  DocTemplateForm: () => import('./DocTemplateForm'),
  DocAuditForm: () => import('./DocAuditForm'),
  CompanyRegistrationsForm: () => import('./CompanyRegistrationsForm'),
  VesselFormForm: () => import('./VesselFormForm')
}
