<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Application Permissions
    |--------------------------------------------------------------------------
    */
//    'nationalities' => [
//        ['id' => 'DUT', 'nationality' => 'Dutch'],
//        ['id' => 'BGL', 'nationality'  => 'Bangladeshi'],
//        ['id' => 'IND', 'nationality'  => 'Indonesian'],
//        ['id' => 'MAS', 'nationality'  => 'Malaysian'],
//        ['id' => 'MYA', 'nationality'  => 'Myanmar'],
//        ['id' => 'PHI', 'nationality'  => 'Filipino'],
//        ['id' => 'SRI', 'nationality'  => 'Sri Lankan'],
//    ],
    'nationalities' => [
        'AD' => ['id' => 	'AD', 'nationality' => 	'Andorian'],
        'AE' => ['id' => 	'AE', 'nationality' => 	'Emirian'],
        'AF' => ['id' => 	'AF', 'nationality' => 	'Afghani'],
        'AI' => ['id' => 	'AI', 'nationality' => 	'Anguillan'],
        'AM' => ['id' => 	'AM', 'nationality' => 	'Armenian'],
        'AO' => ['id' => 	'AO', 'nationality' => 	'Angolian'],
        'AQ' => ['id' => 	'AQ', 'nationality' => 	'Antarctic'],
        'AR' => ['id' => 	'AR', 'nationality' => 	'Argentine'],
        'AS' => ['id' => 	'AS', 'nationality' => 	'Austrian'],
        'AU' => ['id' => 	'AU', 'nationality' => 	'Australian'],
        'AW' => ['id' => 	'AW', 'nationality' => 	'Arubian'],
        'BB' => ['id' => 	'BB', 'nationality' => 	'Barbadian'],
        'BE' => ['id' => 	'BE', 'nationality' => 	'Belgian'],
        'BH' => ['id' => 	'BH', 'nationality' => 	'Bahrainian'],
        'BM' => ['id' => 	'BM', 'nationality' => 	'Bermuda'],
        'BO' => ['id' => 	'BO', 'nationality' => 	'Bolivian'],
        'BR' => ['id' => 	'BR', 'nationality' => 	'Brazilian'],
        'BS' => ['id' => 	'BS', 'nationality' => 	'Bahameese'],
        'BT' => ['id' => 	'BT', 'nationality' => 	'Bhutanese'],
        'BU' => ['id' => 	'BU', 'nationality' => 	'Bulgarian'],
        'BY' => ['id' => 	'BY', 'nationality' => 	'Belarusian'],
        'BZ' => ['id' => 	'BZ', 'nationality' => 	'Belizean'],
        'CA' => ['id' => 	'CA', 'nationality' => 	'Canadian'],
        'CG' => ['id' => 	'CG', 'nationality' => 	'Congolese'],
        'CH' => ['id' => 	'CH', 'nationality' => 	'Chinese'],
        'CH' => ['id' => 	'CH', 'nationality' => 	'Swiss'],
        'CL' => ['id' => 	'CL', 'nationality' => 	'Chilean'],
        'CM' => ['id' => 	'CM', 'nationality' => 	'Cambodian'],
        'CM' => ['id' => 	'CM', 'nationality' => 	'Cameroonian'],
        'CO' => ['id' => 	'CO', 'nationality' => 	'Columbian'],
        'CR' => ['id' => 	'CR', 'nationality' => 	'Czech'],
        'CR' => ['id' => 	'CR', 'nationality' => 	'Costa Rican'],
        'CU' => ['id' => 	'CU', 'nationality' => 	'Cuban'],
        'CY' => ['id' => 	'CY', 'nationality' => 	'Cypriot'],
        'DE' => ['id' => 	'DE', 'nationality' => 	'German'],
        'DK' => ['id' => 	'DK', 'nationality' => 	'Danish'],
        'DM' => ['id' => 	'DM', 'nationality' => 	'Dominican'],
        'EC' => ['id' => 	'EC', 'nationality' => 	'Ecuadorean'],
        'EE' => ['id' => 	'EE', 'nationality' => 	'Estonian'],
        'EG' => ['id' => 	'EG', 'nationality' => 	'Egyptian'],
        'ET' => ['id' => 	'ET', 'nationality' => 	'Ethiopian'],
        'FI' => ['id' => 	'FI', 'nationality' => 	'Finnish'],
        'FJ' => ['id' => 	'FJ', 'nationality' => 	'Fijian'],
        'FR' => ['id' => 	'FR', 'nationality' => 	'French'],
        'GB' => ['id' => 	'GB', 'nationality' => 	'British'],
        'GE' => ['id' => 	'GE', 'nationality' => 	'Georgian'],
        'GH' => ['id' => 	'GH', 'nationality' => 	'Ghanaian'],
        'GN' => ['id' => 	'GN', 'nationality' => 	'Guinean'],
        'GR' => ['id' => 	'GR', 'nationality' => 	'Greek'],
        'GY' => ['id' => 	'GY', 'nationality' => 	'Guyanese'],
        'HK' => ['id' => 	'HK', 'nationality' => 	'Chinese'],
        'HR' => ['id' => 	'HR', 'nationality' => 	'Croatian'],
        'HU' => ['id' => 	'HU', 'nationality' => 	'Hungarian'],
        'IE' => ['id' => 	'IE', 'nationality' => 	'Irish'],
        'IN' => ['id' => 	'IN', 'nationality' => 	'Indian'],
        'IQ' => ['id' => 	'IQ', 'nationality' => 	'Iraqi'],
        'IR' => ['id' => 	'IR', 'nationality' => 	'Iranian'],
        'IS' => ['id' => 	'IS', 'nationality' => 	'Israeli'],
        'IS' => ['id' => 	'IS', 'nationality' => 	'Icelander'],
        'IT' => ['id' => 	'IT', 'nationality' => 	'Italian'],
        'JM' => ['id' => 	'JM', 'nationality' => 	'Jamaican'],
        'JO' => ['id' => 	'JO', 'nationality' => 	'Jordanian'],
        'JP' => ['id' => 	'JP', 'nationality' => 	'Japanese'],
        'KE' => ['id' => 	'KE', 'nationality' => 	'Kenyan'],
        'KO' => ['id' => 	'KO', 'nationality' => 	'Korean'],
        'KW' => ['id' => 	'KW', 'nationality' => 	'Kuwaiti'],
        'KZ' => ['id' => 	'KZ', 'nationality' => 	'Kazakhstani'],
        'KZ' => ['id' => 	'KZ', 'nationality' => 	'Kazakhstani'],
        'LB' => ['id' => 	'LB', 'nationality' => 	'Lebanese'],
        'LT' => ['id' => 	'LT', 'nationality' => 	'Lithunian'],
        'LU' => ['id' => 	'LU', 'nationality' => 	'Luxembourger'],
        'MA' => ['id' => 	'MA', 'nationality' => 	'Moroccan'],
        'MC' => ['id' => 	'MC', 'nationality' => 	'Monacan'],
        'ME' => ['id' => 	'ME', 'nationality' => 	'Mexican'],
        'MM' => ['id' => 	'MM', 'nationality' => 	'Mayanmarese'],
        'MN' => ['id' => 	'MN', 'nationality' => 	'Mongolian'],
        'MO' => ['id' => 	'MO', 'nationality' => 	'Macau'],
        'MU' => ['id' => 	'MU', 'nationality' => 	'Mauritian'],
        'MV' => ['id' => 	'MV', 'nationality' => 	'Maldivan'],
        'NA' => ['id' => 	'NA', 'nationality' => 	'Namibian'],
        'NG' => ['id' => 	'NG', 'nationality' => 	'Nigerian'],
        'NO' => ['id' => 	'NO', 'nationality' => 	'Norwegian'],
        'NP' => ['id' => 	'NP', 'nationality' => 	'Nepalese'],
        'NZ' => ['id' => 	'NZ', 'nationality' => 	'New Zealander'],
        'OM' => ['id' => 	'OM', 'nationality' => 	'Omani'],
        'PA' => ['id' => 	'PA', 'nationality' => 	'Panamanian'],
        'PE' => ['id' => 	'PE', 'nationality' => 	'Peruvian'],
        'PK' => ['id' => 	'PK', 'nationality' => 	'Pakistani'],
        'PO' => ['id' => 	'PO', 'nationality' => 	'Polish'],
        'PT' => ['id' => 	'PT', 'nationality' => 	'Portugees'],
        'PY' => ['id' => 	'PY', 'nationality' => 	'Paraguayan'],
        'QA' => ['id' => 	'QA', 'nationality' => 	'Qatari'],
        'RO' => ['id' => 	'RO', 'nationality' => 	'Romanian'],
        'RU' => ['id' => 	'RU', 'nationality' => 	'Russian'],
        'SA' => ['id' => 	'SA', 'nationality' => 	'Saudi Arabian'],
        'SC' => ['id' => 	'SC', 'nationality' => 	'Seychellois'],
        'SE' => ['id' => 	'SE', 'nationality' => 	'Swedish'],
        'SG' => ['id' => 	'SG', 'nationality' => 	'Singaporean'],
        'SK' => ['id' => 	'SK', 'nationality' => 	'Slovakian'],
        'SN' => ['id' => 	'SN', 'nationality' => 	'Senegalese'],
        'SO' => ['id' => 	'SO', 'nationality' => 	'Somali'],
        'SP' => ['id' => 	'SP', 'nationality' => 	'Spanish'],
        'TH' => ['id' => 	'TH', 'nationality' => 	'Thai'],
        'TN' => ['id' => 	'TN', 'nationality' => 	'Tunisian'],
        'TR' => ['id' => 	'TR', 'nationality' => 	'Turkish'],
        'TW' => ['id' => 	'TW', 'nationality' => 	'Taiwanese'],
        'TZ' => ['id' => 	'TZ', 'nationality' => 	'Tanzanian'],
        'UA' => ['id' => 	'UA', 'nationality' => 	'Ukrainian'],
        'UG' => ['id' => 	'UG', 'nationality' => 	'Ugandan'],
        'US' => ['id' => 	'US', 'nationality' => 	'American'],
        'UY' => ['id' => 	'UY', 'nationality' => 	'Uruguayan'],
        'UZ' => ['id' => 	'UZ', 'nationality' => 	'Uzbekistani'],
        'VE' => ['id' => 	'VE', 'nationality' => 	'Venezuelan'],
        'VN' => ['id' => 	'VN', 'nationality' => 	'Vietnamese'],
        'YE' => ['id' => 	'YE', 'nationality' => 	'Yemeni'],
        'ZA' => ['id' => 	'ZA', 'nationality' => 	'South African'],
        'ZM' => ['id' => 	'ZM', 'nationality' => 	'Zambian'],
        'ZW' => ['id' => 	'ZW', 'nationality' => 	'Zimbabwean'],
        'DUT'=> ['id' => 'DUT', 'nationality' => 'Dutch'],
        'BGL'=> ['id' => 'BGL', 'nationality'  => 'Bangladeshi'],
        'IND'=> ['id' => 'IND', 'nationality'  => 'Indonesian'],
        'MAS'=> ['id' => 'MAS', 'nationality'  => 'Malaysian'],
        'MYA'=> ['id' => 'MYA', 'nationality'  => 'Myanmar'],
        'PHI'=> ['id' => 'PHI', 'nationality'  => 'Filipino'],
        'SRI'=> ['id' => 'SRI', 'nationality'  => 'Sri Lankan'],
        'SYR'=> ['id' => 'SYR', 'nationality'  => 'Syrian'],
        'OTH'=> ['id' => 'OTH', 'nationality'  => 'Other'],
    ],
    'all_countries' => [
        'Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegowina', 'Botswana', 'Bouvet Island', 'Brazil', 'British Indian Ocean Territory', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island', 'Cocos (Keeling) Islands', 'Colombia', 'Comoros', 'Congo', 'Congo, the Democratic Republic of the', 'Cook Islands', 'Costa Rica', "Cote d'Ivoire", 'Croatia (Hrvatska)', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Falkland Islands (Malvinas)', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'France Metropolitan', 'French Guiana', 'French Polynesia', 'French Southern Territories', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heard and Mc Donald Islands', 'Holy See (Vatican City State)', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Democratic People's Republic of", 'Korea, Republic of', 'Kuwait', 'Kyrgyzstan', "Lao, People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libyan Arab Jamahiriya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macau', 'Macedonia, The Former Yugoslav Republic of', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico', 'Micronesia, Federated States of', 'Moldova, Republic of', 'Monaco', 'Mongolia', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'Netherlands Antilles', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russian Federation', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia (Slovak Republic)', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Georgia and the South Sandwich Islands', 'Spain', 'Sri Lanka', 'St. Helena', 'St. Pierre and Miquelon', 'Sudan', 'Suriname', 'Svalbard and Jan Mayen Islands', 'Swaziland', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Taiwan, Province of China', 'Tajikistan', 'Tanzania, United Republic of', 'Thailand', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'United States Minor Outlying Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Virgin Islands (British)', 'Virgin Islands (U.S.)', 'Wallis and Futuna Islands', 'Western Sahara', 'Yemen', 'Yugoslavia', 'Zambia', 'Zimbabwe',
    ],
    'all_nationalities' => [
        'Afghan',
        'Albanian',
        'Algerian',
        'American',
        'Andorran',
        'Angolan',
        'Antiguans',
        'Argentinean',
        'Armenian',
        'Australian',
        'Austrian',
        'Azerbaijani',
        'Bahamian',
        'Bahraini',
        'Bangladeshi',
        'Barbadian',
        'Barbudans',
        'Batswana',
        'Belarusian',
        'Belgian',
        'Belizean',
        'Beninese',
        'Bhutanese',
        'Bolivian',
        'Bosnian',
        'Brazilian',
        'British',
        'Bruneian',
        'Bulgarian',
        'Burkinabe',
        'Burmese',
        'Burundian',
        'Cambodian',
        'Cameroonian',
        'Canadian',
        'Cape Verdean',
        'Central African',
        'Chadian',
        'Chilean',
        'Chinese',
        'Colombian',
        'Comoran',
        'Congolese',
        'Costa Rican',
        'Croatian',
        'Cuban',
        'Cypriot',
        'Czech',
        'Danish',
        'Djibouti',
        'Dominican',
        'Dutch',
        'East Timorese',
        'Ecuadorean',
        'Egyptian',
        'Emirian',
        'Equatorial Guinean',
        'Eritrean',
        'Estonian',
        'Ethiopian',
        'Fijian',
        'Filipino',
        'Finnish',
        'French',
        'Gabonese',
        'Gambian',
        'Georgian',
        'German',
        'Ghanaian',
        'Greek',
        'Grenadian',
        'Guatemalan',
        'Guinea-Bissauan',
        'Guinean',
        'Guyanese',
        'Haitian',
        'Herzegovinian',
        'Honduran',
        'Hungarian',
        'I-Kiribati',
        'Icelander',
        'Indian',
        'Indonesian',
        'Iranian',
        'Iraqi',
        'Irish',
        'Israeli',
        'Italian',
        'Ivorian',
        'Jamaican',
        'Japanese',
        'Jordanian',
        'Kazakhstani',
        'Kenyan',
        'Kittian and Nevisian',
        'Kuwaiti',
        'Kyrgyz',
        'Laotian',
        'Latvian',
        'Lebanese',
        'Liberian',
        'Libyan',
        'Liechtensteiner',
        'Lithuanian',
        'Luxembourger',
        'Macedonian',
        'Malagasy',
        'Malawian',
        'Malaysian',
        'Maldivan',
        'Malian',
        'Maltese',
        'Marshallese',
        'Mauritanian',
        'Mauritian',
        'Mexican',
        'Micronesian',
        'Moldovan',
        'Monacan',
        'Mongolian',
        'Moroccan',
        'Mosotho',
        'Motswana',
        'Mozambican',
        'Namibian',
        'Nauruan',
        'Nepalese',
        'New Zealander',
        'Nicaraguan',
        'Nigerian',
        'Nigerien',
        'North Korean',
        'Northern Irish',
        'Norwegian',
        'Omani',
        'Pakistani',
        'Palauan',
        'Panamanian',
        'Papua New Guinean',
        'Paraguayan',
        'Peruvian',
        'Polish',
        'Portuguese',
        'Qatari',
        'Romanian',
        'Russian',
        'Rwandan',
        'Saint Lucian',
        'Salvadoran',
        'Samoan',
        'San Marinese',
        'Sao Tomean',
        'Saudi',
        'Scottish',
        'Senegalese',
        'Serbian',
        'Seychellois',
        'Sierra Leonean',
        'Singaporean',
        'Slovakian',
        'Slovenian',
        'Solomon Islander',
        'Somali',
        'South African',
        'South Korean',
        'Spanish',
        'Sri Lankan',
        'Sudanese',
        'Surinamer',
        'Swazi',
        'Swedish',
        'Swiss',
        'Syrian',
        'Taiwanese',
        'Tajik',
        'Tanzanian',
        'Thai',
        'Togolese',
        'Tongan',
        'Trinidadian/Tobagonian',
        'Tunisian',
        'Turkish',
        'Tuvaluan',
        'Ugandan',
        'Ukrainian',
        'Uruguayan',
        'Uzbekistani',
        'Venezuelan',
        'Vietnamese',
        'Welsh',
        'Yemenite',
        'Zambian',
        'Zimbabwean',
    ],

    'races' => [
        'Arabs',
    ],

    'religions' => [
        'Muslim',
        'Christian',
        'Buddhist',
        'Hindu',
        'Jewish',
        'Atheist',
        'Indian',
        'Other',
    ],
    'genders' => [
        'Male',
        'Female',
    ],
    'marital_statuses' => [
        'Married',
        'Single',
        'Divorced',
        'Widowed',
    ],
    'vessel_certificate_types' => [
        'DOC',
        'SMC',
        'ISSC',
        'COR MY',
        'COR MNG',
        'SMD',
        'IAFS',
        'CSR',
        'SRSL',
        'COC',
        'CSSC',
        'ITC (1969)',
        'IOPP',
        'ILL',
        'CSSE',
        'CSSR',
        'COECS',
        'IAPP',
        'ISPP (SEWAGE)',
        'MLC CERTIFICATE',
        'IEEC',
        'SSCE',
        'MCC',
        'DSL',
        'TESTING SSAS',
        'WRCC',
        'BCC',
        'MARINE P&I',
        'MARINE H&M',
        'SO INSURANCE',
        'SF INSURANCE',
        'SBM',
        'SCM',
        'EIAPP',
        'IBWM',
        'MSO CARGO SHIP EXEMPTION',
        'CAMN',
        'MSMC'
    ],
    'vessel_insurance_types' => [
        'MARINE HULL PACKAGE INSURANCE',
        'MORTGAGEE INTEREST INSURANCE',
        'PROTECTION & INDEMNITY',
        'BUNKER CONVENTION BLUE CARD',
        'WRECK REMOVAL',
        'MLC REG 4.2',
        'MLC REG 4.2 STANDARD A4.2.1',
        'MLC REG 2.5.2'
    ],
];
